// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Northwind.DAL.Abstractions.Entities;

namespace Northwind.DAL.DatabaseFirst.Entities
{
    public partial class CategorySalesFor1997 : Entity
    {
        public string CategoryName { get; set; }
        public decimal? CategorySales { get; set; }
    }
}