// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Northwind.DAL.Abstractions.Entities;

namespace Northwind.DAL.DatabaseFirst.Entities
{
    public partial class ProductsAboveAveragePrice : Entity
    {
        public string ProductName { get; set; }
        public decimal? UnitPrice { get; set; }
    }
}