//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.DAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.DAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order..
        /// </summary>
        public static string OrderRepository_Add_Invalid_order_ {
            get {
                return ResourceManager.GetString("OrderRepository_Add_Invalid_order_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order id..
        /// </summary>
        public static string OrderRepository_CustOrderDetail_Invalid_order_id_ {
            get {
                return ResourceManager.GetString("OrderRepository_CustOrderDetail_Invalid_order_id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer orders details not found..
        /// </summary>
        public static string OrderRepository_CustOrderDetail_The_customer_orders_details_not_found_ {
            get {
                return ResourceManager.GetString("OrderRepository_CustOrderDetail_The_customer_orders_details_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer id..
        /// </summary>
        public static string OrderRepository_CustOrderHist_Invalid_customer_id_ {
            get {
                return ResourceManager.GetString("OrderRepository_CustOrderHist_Invalid_customer_id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer order hist not found..
        /// </summary>
        public static string OrderRepository_CustOrderHist_The_customer_order_hist_not_found_ {
            get {
                return ResourceManager.GetString("OrderRepository_CustOrderHist_The_customer_order_hist_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders with Completed status cannot be deleted.
        /// </summary>
        public static string OrderRepository_Delete_Orders_with_Completed_status_cannot_be_deleted {
            get {
                return ResourceManager.GetString("OrderRepository_Delete_Orders_with_Completed_status_cannot_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order with id = {0} not found..
        /// </summary>
        public static string OrderRepository_Get_ {
            get {
                return ResourceManager.GetString("OrderRepository_Get_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order id..
        /// </summary>
        public static string OrderRepository_Get_Invalid_order_id_ {
            get {
                return ResourceManager.GetString("OrderRepository_Get_Invalid_order_id_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The orders not found..
        /// </summary>
        public static string OrderRepository_GetAll_The_orders_not_found_ {
            get {
                return ResourceManager.GetString("OrderRepository_GetAll_The_orders_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status can&apos;t be changed to CompletedStatus..
        /// </summary>
        public static string OrderRepository_SetCompletedStatus_Status_can_t_be_changed_to_CompletedStatus_ {
            get {
                return ResourceManager.GetString("OrderRepository_SetCompletedStatus_Status_can_t_be_changed_to_CompletedStatus_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in the order with the NewStatus can the status be changed to InWork..
        /// </summary>
        public static string OrderRepository_SetInWorkStatus_Only_in_the_order_with_the_NewStatus_can_the_status_be_changed_to_InWork_ {
            get {
                return ResourceManager.GetString("OrderRepository_SetInWorkStatus_Only_in_the_order_with_the_NewStatus_can_the_stat" +
                        "us_be_changed_to_InWork_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order..
        /// </summary>
        public static string OrderRepository_Update_Invalid_order_ {
            get {
                return ResourceManager.GetString("OrderRepository_Update_Invalid_order_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only orders with New status can be changed.
        /// </summary>
        public static string OrderRepository_Update_Only_orders_with_New_status_can_be_changed {
            get {
                return ResourceManager.GetString("OrderRepository_Update_Only_orders_with_New_status_can_be_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders with statuses InWork and Completed cannot be changed.
        /// </summary>
        public static string OrderRepository_Update_Orders_with_statuses_InWork_and_Completed_cannot_be_changed {
            get {
                return ResourceManager.GetString("OrderRepository_Update_Orders_with_statuses_InWork_and_Completed_cannot_be_change" +
                        "d", resourceCulture);
            }
        }
    }
}
