//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileVisitor.ConsoleUI.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileVisitor.ConsoleUI.Resources.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DIRECTORY FINDED] .
        /// </summary>
        public static string Application_OnDirectoryFinded_Handler__DIRECTORY_FINDED__ {
            get {
                return ResourceManager.GetString("Application_OnDirectoryFinded_Handler__DIRECTORY_FINDED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FILE FINDED] .
        /// </summary>
        public static string Application_OnFileFinded_Handler__FILE_FINDED__ {
            get {
                return ResourceManager.GetString("Application_OnFileFinded_Handler__FILE_FINDED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FILTERED] .
        /// </summary>
        public static string Application_OnFilteredDirectoryFinded_Handler__FILTERED__ {
            get {
                return ResourceManager.GetString("Application_OnFilteredDirectoryFinded_Handler__FILTERED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [FILTERED] .
        /// </summary>
        public static string Application_OnFilteredFileFinded_Handler__FILTERED__ {
            get {
                return ResourceManager.GetString("Application_OnFilteredFileFinded_Handler__FILTERED__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SEARCH HAS FINISHED].
        /// </summary>
        public static string Application_OnFinished_Handler__SEARCH_HAS_FINISHED_ {
            get {
                return ResourceManager.GetString("Application_OnFinished_Handler__SEARCH_HAS_FINISHED_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SEARCH HAS STARTED].
        /// </summary>
        public static string Application_OnStarted_Handler__SEARCH_HAS_STARTED_ {
            get {
                return ResourceManager.GetString("Application_OnStarted_Handler__SEARCH_HAS_STARTED_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Visitor - console application - {0}.
        /// </summary>
        public static string Application_Run_File_Visitor___console_application_ {
            get {
                return ResourceManager.GetString("Application_Run_File_Visitor___console_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled custom exception - {0}.
        /// </summary>
        public static string Application_Run_Handled_custom_exception____0_ {
            get {
                return ResourceManager.GetString("Application_Run_Handled_custom_exception____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception - {0}.
        /// </summary>
        public static string Application_Run_Unhandled_exception____0_ {
            get {
                return ResourceManager.GetString("Application_Run_Unhandled_exception____0_", resourceCulture);
            }
        }
    }
}
